Task model, controller, migration and JWT authentication added
IlijaT/TodoApp pull request #1
Opened 2018-06-27 12:15 UTC by IlijaT

2018-06-27 12:21 UTC, calico-anne requested changes

2018-06-27 12:21 UTC, volkova229 commented on routes/api.php
> +Route::apiResource('/tasks', "TasksController");
Navodnici samo da budu `'` kao i iznad. Budi konzistentan :)

2018-06-27 12:30 UTC, calico-anne requested changes

2018-06-27 12:30 UTC, volkova229 commented on app/Task.php
> +    //
Ovde moras napraviti 
`protected $fillable = [ 'title' ...]`;
Sa svim poljima koje zelis da mozes da upisujes u bazu. Npr. id ti nece trebati ovde :)

2018-06-27 12:30 UTC, volkova229 commented on app/Task.php
> +class Task extends Model
Takodje, treba da se postavi veza izmedju user-a i task-a.
Task pripada samo jednom user-u. :) Pogledaj po dokumentaciji kako to da postignes.

2018-06-27 12:30 UTC, volkova229 commented on database/migrations/2018_06_27_080510_create_tasks_table.php
> +            $table->increments('id');
Samim tim sto task pripada jednom user-u, nekako moramo da spojimo te tabele. 
Znaci na tabeli `tasks` treba da imas neki `user_id` 
`$table->unsignedInteger('user_id')`
Laravel generalno konta sa cim je to u vezi kad postavis relacije kako treba.

2018-06-27 12:30 UTC, volkova229 commented on app/User.php
> +    }
Znaci ovde negde treba da postavis i relaciju izmedju user-a i task-ova. Jedan user moze da ima vise taskova.

2018-06-27 12:30 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
> +        //
U ovoj metodi treba da vratis sve taskove trenutno ulogovanog korisnika.

2018-06-27 12:30 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
> +        //
Ovde treba da sacuvas novi task u  bazu. Podaci ce biti na $request-u. Mozes probati kroz postman da gadjas rutu, a ovde da ostavljas `\Log::info($request)` da vidis sta ti stize.

2018-06-27 12:30 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
> +        //
Ovde treba da update-ujes task. Izvuces `id` i 'prepises' nove informacije o tasku.

2018-06-27 12:30 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
> +        //
Ovde brises task

2018-06-28 11:05 UTC, calico-anne requested changes

2018-06-28 11:05 UTC, calico-anne commented on app/Http/Controllers/AuthController.php
> +       \Log::info($user);
Ovo su ostaci koji uvek treba da se brisu

2018-06-28 11:05 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
> +        return response()->json(['tasks' =>  $tasks], 200);
E sad, umesto svega ovoga

`return Auth::user()->tasks`;

2018-06-28 11:05 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
> +        return response()->json(['task' =>  $newTask], 201);
Umesto svega ovoga

```
$request->request->add(['user_id' => Auth::id()]);

return User::create($request->all());
```

2018-06-28 11:05 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
> +    public function show($id)
Umesto svega:

`return Task::findOrFail($id);`

2018-06-28 11:05 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
>      public function destroy($id)
Umesto svega ovoga

`return Task::destroy($id)`;

2018-06-28 11:05 UTC, volkova229 commented on app/Http/Controllers/TasksController.php
> +    public function update(Request $request, $id)
Umesto svega ovoga

```
return Task::findOrFail($id)->update(request->all());
```

2018-06-28 11:06 UTC, calico-anne requested changes

2018-06-28 11:06 UTC, volkova229 commented on app/Task.php
> +        'title', 'description', 'priority',
Fali ti ovde `user_id`

2018-06-28 14:29 UTC, calico-anne approved these changes

2018-06-28 14:29 UTC, merged